services:

### Net-Tools Container #######################################

    net-tools:
      build:
        context: ./mysql
      networks:
        - frontend
        - backend


### MySQL for UnitTests ##################################
    mysql-tests:
      restart: always
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      tmpfs:
        - /var/lib/mysql  # Creating the database in RAM
      volumes:
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      networks:
        - backend


### Nginx-Proxy ############################################
    nginx-proxy:
      image: jwilder/nginx-proxy:alpine
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ${DATA_PATH_HOST}/selfsigned/certs:/etc/nginx/certs
        - ${NGINX_PROXY_CONF}:/etc/nginx/conf.d/my_proxy.conf:ro
        - ${NGINX_PROXY_VHOST_PATH}:/etc/nginx/vhost.d:ro
      networks:
        - frontend
        - backend


### NGINX Server (changes) #########################################
    nginx:
      ports: !reset []
      depends_on:
        - nginx-proxy
        - php-fpm-56
      environment:
        - VIRTUAL_HOST=${NGINX_VIRTUAL_HOSTS}


### Apache Server (changes) ########################################
    apache2:
      ports: !reset []
      depends_on:
        - nginx-proxy
      environment:
        - VIRTUAL_HOST=${NGINX_VIRTUAL_HOSTS}


### phpMyAdmin (changes) ###########################################
    phpmyadmin:
      ports: !reset []
      depends_on:
        - nginx-proxy
      environment:
        - VIRTUAL_HOST=${PMA_VIRTUAL_HOST}
        - PMA_HOST=db
      links:
        - "${PMA_DB_ENGINE}:db"


### Adminer (changes) ###########################################
    adminer:
      ports: !reset []
      environment:
        - VIRTUAL_HOST=${ADM_VIRTUAL_HOST}
      depends_on:
        - "${ADM_DEFAULT_SERVER}"
        - nginx-proxy


### pgAdmin (changes) ##############################################
    pgadmin:
      ports: !reset []
      environment:
        - VIRTUAL_HOST=${PGA_VIRTUAL_HOST}
      depends_on:
        - nginx-proxy


### PHP-FPM (changes) ##############################################
    php-fpm:
      volumes:
        - ./php-fpm/xdebug3.ini:/usr/local/etc/php/conf.d/xdebug.ini


### PHP-FPM 5.6 ##############################################
    php-fpm-56:
      hostname: devphp56
      build:
        context: ./php-fpm
        args:
          - LARADOCK_PHP_VERSION=5.6
          - LARADOCK_PHALCON_VERSION=${PHALCON_VERSION}
          - INSTALL_PCNTL=true
          - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
          - INSTALL_PHPDBG=${PHP_FPM_INSTALL_PHPDBG}
          - INSTALL_BLACKFIRE=${INSTALL_BLACKFIRE}
          - INSTALL_SSH2=${PHP_FPM_INSTALL_SSH2}
          - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
          - INSTALL_XSL=${PHP_FPM_INSTALL_XSL}
          - INSTALL_IMAP=${PHP_FPM_INSTALL_IMAP}
          - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO}
          - INSTALL_AMQP=${PHP_FPM_INSTALL_AMQP}
          - INSTALL_CASSANDRA=${PHP_FPM_INSTALL_CASSANDRA}
          - INSTALL_MSSQL=${PHP_FPM_INSTALL_MSSQL}
          - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
          - INSTALL_GMP=${PHP_FPM_INSTALL_GMP}
          - INSTALL_PHPREDIS=false
          - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
          - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
          - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
          - INSTALL_AEROSPIKE=${PHP_FPM_INSTALL_AEROSPIKE}
          - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
          - INSTALL_PGSQL=${PHP_FPM_INSTALL_PGSQL}
          - INSTALL_PG_CLIENT=${PHP_FPM_INSTALL_PG_CLIENT}
          - INSTALL_POSTGIS=${PHP_FPM_INSTALL_POSTGIS}
          - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
          - INSTALL_GHOSTSCRIPT=${PHP_FPM_INSTALL_GHOSTSCRIPT}
          - INSTALL_LDAP=${PHP_FPM_INSTALL_LDAP}
          - INSTALL_PHALCON=${PHP_FPM_INSTALL_PHALCON}
          - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
          - INSTALL_TAINT=${PHP_FPM_INSTALL_TAINT}
          - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
          - INSTALL_IMAGEMAGICK=false
          - INSTALL_CALENDAR=${PHP_FPM_INSTALL_CALENDAR}
          - INSTALL_FAKETIME=${PHP_FPM_INSTALL_FAKETIME}
          - INSTALL_IONCUBE=${PHP_FPM_INSTALL_IONCUBE}
          - INSTALL_APCU=${PHP_FPM_INSTALL_APCU}
          - INSTALL_YAML=${PHP_FPM_INSTALL_YAML}
          - INSTALL_RDKAFKA=${PHP_FPM_INSTALL_RDKAFKA}
          - INSTALL_ADDITIONAL_LOCALES=${PHP_FPM_INSTALL_ADDITIONAL_LOCALES}
          - INSTALL_MYSQL_CLIENT=${PHP_FPM_INSTALL_MYSQL_CLIENT}
          - INSTALL_PING=${PHP_FPM_INSTALL_PING}
          - INSTALL_SSHPASS=${PHP_FPM_INSTALL_SSHPASS}
          - ADDITIONAL_LOCALES=${PHP_FPM_ADDITIONAL_LOCALES}
          - INSTALL_FFMPEG=${PHP_FPM_FFMPEG}
          - INSTALL_XHPROF=${PHP_FPM_INSTALL_XHPROF}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ./php-fpm/php5.6.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      expose:
        - "9000"
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - DOCKER_HOST=tcp://docker-in-docker:2375
        - FAKETIME=${PHP_FPM_FAKETIME}
      depends_on:
        - workspace
      networks:
        - backend
      links:
        - docker-in-docker
